import {
  BookOpen,
  Calendar,
  Cloud,
  Code,
  Diamond,
  DiceFive as Dices,
  Dog,
  FileCode,
  GameController as Gamepad2,
  ImageSquare as ImageIcon,
  Stack as Layers,
  Leaf,
  List,
  ListChecks,
  Lock,
  EnvelopeSimple as Mail,
  ChatsCircle as MessagesSquare,
  Mountains as Mountain,
  MusicNotes as Music,
  Broadcast as Radio,
  Path as Route,
  HardDrives as Server,
  ShoppingCart,
  Note as StickyNote,
  Terminal as TerminalSquare,
  Ticket,
  Trophy,
  Users,
  Wallet,
} from "@phosphor-icons/react";
import type { ReactNode } from "react";

const iconClass = "h-5 w-5";

const iconMap: Record<string, ReactNode> = {
  notes: <StickyNote className={iconClass} />,
  shoppingCart: <ShoppingCart className={iconClass} />,
  diamond: <Diamond className={iconClass} />,
  messages: <MessagesSquare className={iconClass} />,
  wallet: <Wallet className={iconClass} />,
  photo: <ImageIcon className={iconClass} />,
  trophy: <Trophy className={iconClass} />,
  broadcast: <Radio className={iconClass} />,
  calendar: <Calendar className={iconClass} />,
  users: <Users className={iconClass} />,
  route: <Route className={iconClass} />,
  mountain: <Mountain className={iconClass} />,
  ticket: <Ticket className={iconClass} />,
  checklist: <ListChecks className={iconClass} />,
  leaf: <Leaf className={iconClass} />,
  lock: <Lock className={iconClass} />,
  list: <List className={iconClass} />,
  book: <BookOpen className={iconClass} />,
  mail: <Mail className={iconClass} />,
  cloud: <Cloud className={iconClass} />,
  device: <Gamepad2 className={iconClass} />,
  music: <Music className={iconClass} />,
  dice: <Dices className={iconClass} />,
  dog: <Dog className={iconClass} />,
  terminal: <TerminalSquare className={iconClass} />,
  markdown: <FileCode className={iconClass} />,
  code: <Code className={iconClass} />,
  server: <Server className={iconClass} />,
  layers: <Layers className={iconClass} />,
};

export const getIcon = (key?: string): ReactNode =>
  (key && iconMap[key]) || <Code className={iconClass} />;
