import {
  BookOpen,
  Calendar,
  Cloud,
  Code2,
  Diamond,
  Dices,
  Dog,
  FileCode2,
  Gamepad2,
  Image as ImageIcon,
  Layers,
  Leaf,
  List,
  ListChecks,
  Lock,
  Mail,
  MessagesSquare,
  Mountain,
  Music,
  Radio,
  Route,
  Server,
  ShoppingCart,
  StickyNote,
  TerminalSquare,
  Ticket,
  Trophy,
  Users,
  Wallet,
} from "lucide-react";
import type { ReactNode } from "react";

const iconClass = "h-5 w-5";

const iconMap: Record<string, ReactNode> = {
  notes: <StickyNote className={iconClass} />,
  shoppingCart: <ShoppingCart className={iconClass} />,
  diamond: <Diamond className={iconClass} />,
  messages: <MessagesSquare className={iconClass} />,
  wallet: <Wallet className={iconClass} />,
  photo: <ImageIcon className={iconClass} />,
  trophy: <Trophy className={iconClass} />,
  broadcast: <Radio className={iconClass} />,
  calendar: <Calendar className={iconClass} />,
  users: <Users className={iconClass} />,
  route: <Route className={iconClass} />,
  mountain: <Mountain className={iconClass} />,
  ticket: <Ticket className={iconClass} />,
  checklist: <ListChecks className={iconClass} />,
  leaf: <Leaf className={iconClass} />,
  lock: <Lock className={iconClass} />,
  list: <List className={iconClass} />,
  book: <BookOpen className={iconClass} />,
  mail: <Mail className={iconClass} />,
  cloud: <Cloud className={iconClass} />,
  device: <Gamepad2 className={iconClass} />,
  music: <Music className={iconClass} />,
  dice: <Dices className={iconClass} />,
  dog: <Dog className={iconClass} />,
  terminal: <TerminalSquare className={iconClass} />,
  markdown: <FileCode2 className={iconClass} />,
  code: <Code2 className={iconClass} />,
  server: <Server className={iconClass} />,
  layers: <Layers className={iconClass} />,
};

export const getIcon = (key?: string): ReactNode =>
  (key && iconMap[key]) || <Code2 className={iconClass} />;
