import {
  IconBook,
  IconMarkdown,
  IconBroadcast,
  IconCalendar,
  IconChecklist,
  IconCloud,
  IconCode,
  IconDeviceGamepad,
  IconDiamond,
  IconDice,
  IconDog,
  IconLeaf,
  IconList,
  IconLock,
  IconMail,
  IconMessages,
  IconMountain,
  IconMusic,
  IconNote,
  IconPhoto,
  IconRoute,
  IconServer,
  IconShoppingCart,
  IconStack2,
  IconTerminal2,
  IconTicket,
  IconTrophy,
  IconUsers,
  IconWallet,
} from "@tabler/icons-react";
import type { ReactNode } from "react";

const iconMap: Record<string, ReactNode> = {
  notes: <IconNote size={20} stroke={1.4} />,
  shoppingCart: <IconShoppingCart size={20} stroke={1.4} />,
  diamond: <IconDiamond size={20} stroke={1.4} />,
  messages: <IconMessages size={20} stroke={1.4} />,
  wallet: <IconWallet size={20} stroke={1.4} />,
  photo: <IconPhoto size={20} stroke={1.4} />,
  trophy: <IconTrophy size={20} stroke={1.4} />,
  broadcast: <IconBroadcast size={20} stroke={1.4} />,
  calendar: <IconCalendar size={20} stroke={1.4} />,
  users: <IconUsers size={20} stroke={1.4} />,
  route: <IconRoute size={20} stroke={1.4} />,
  mountain: <IconMountain size={20} stroke={1.4} />,
  ticket: <IconTicket size={20} stroke={1.4} />,
  checklist: <IconChecklist size={20} stroke={1.4} />,
  leaf: <IconLeaf size={20} stroke={1.4} />,
  lock: <IconLock size={20} stroke={1.4} />,
  list: <IconList size={20} stroke={1.4} />,
  book: <IconBook size={20} stroke={1.4} />,
  mail: <IconMail size={20} stroke={1.4} />,
  cloud: <IconCloud size={20} stroke={1.4} />,
  device: <IconDeviceGamepad size={20} stroke={1.4} />,
  music: <IconMusic size={20} stroke={1.4} />,
  dice: <IconDice size={20} stroke={1.4} />,
  dog: <IconDog size={20} stroke={1.4} />,
  terminal: <IconTerminal2 size={20} stroke={1.4} />,
  markdown: <IconMarkdown size={20} stroke={1.4} />,
  code: <IconCode size={20} stroke={1.4} />,
  server: <IconServer size={20} stroke={1.4} />,
  layers: <IconStack2 size={20} stroke={1.4} />,
};

export const getIcon = (key?: string): ReactNode =>
  (key && iconMap[key]) || <IconCode size={20} stroke={1.4} />;
